travis:
  secure:
    BINSTAR_TOKEN: t8OH4J1xEIBptH8WS+Ur3Z5JHnOTHYfsNbeNDNYjYF27P4VzH77x+71SxUOVI8xJ7ciAhCa1ZgkYKiKsX2Dem9tpiyc5VcFoWu9yqbeJvNmkfy8ecws1lxDRfKJMBdULttv4TlI7ivvAnL2cYY26qB3eM99LjXMo1eHVJUxbDfSu9IqTC7CxxLnk4ZqcGec1epaTBHll8wDacvkc+DfyWun9D6B5LyLCDrofRnpwAKQyTBfFB0OR8pMZxfDpJNOml46I4NDLf9KeCqOln7bAl8+p9BL+ermhKREmDU0Y0Ri4Qo5uqMAi+R1r2mc/hT04Jq4oU0f8vC2ZFt9LMsfOBsL5Oc2e/KsCts7KqRLBpVAIxCGAooemIPV7OIRfaxy9bRJpo/6omqJod4p8hAt6HtB2bnZvEt7GnDpx6UmMq6oSwmTyOW+WKWklbcANwE7RE5s3jWjxH3Hbg2sCUQfd8YStwm8YfZg2X+iVifxwCyWJoqTzR7E1DwxjujFxb3sM8N3swQCUp1ddiFEkK1yxyHZW/zhCp7WZ5BbD8RwnLVOrlrfioAYxI0N3ItiDwEpFumAGOerynjJnXBndiB7IUgIYtjf2x/McyXDl5leA/EuHxWhxy6XAVNULKqmbqF1G95VjdPGSthe8SsR92ucrKguk0VOhW35schKj/6MMp8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
