travis:
  secure:
    BINSTAR_TOKEN: jqxtfyxMsefmR4D4bi/E4NhTcc3sX/Rvwxczh9UzTBJJOY6LHTEu/JFQ1NaMToBDyNXO99gkFJ9d7KTrMtQ/R9ungRZ29xLQfKckrKlS07oW7dugM47OVjBVIG+8EVzKOa+xTSnG6wmtdSNVK/A9LTrcYtPfuHM4Hjczh93aZXzM7XxDbG3qfIl/NzXgtyfqo8x/hmM6dOqzejpejcL1Xa4/b4NZYh+3Btn7cMjF6zPnQhAAAN6qxzlJlKdCeV9UMqrBX0y3V7DfPYd1RxoOxPq5AdCo9beXEf+dCX9SZoW6aoxmpTA+u2ha7ynJ002euOVd6oy2e+fqTCMUscEEbsFR4CgImwE8y/MTP383HoDyQGcveU9HkH3fZnr16GfAUBmVPnpYIyyvB3R0t3cF/cbJEQP3kv1B2vPeZuvVNQLoaYnn1IxcGQ5OYjPpfMkYxXTS1Q/vRgrsuUvpuiMp+ynvZfuPHdfPlJi0gOAPtI0PelsUZ+4AwqBVYRmblEe3DRIVYIIr2nckIUOw4Jhcv8ml/pj0C+r68SyrTnuuQSWLtCF+pBw8yKkIpTdDxTs7UQpfRHoEGF6jJf5l4YSDFVyC91Cxb+CgcXuRS5L8HD/Edd0iiHNemJlROUlgzXgF+JCtzYAQ2TTM6J3oLkBt8ISwibvTC/vwny/K2+t4l9M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
